### ISSUE TITLE
点击菜单中空白格子弹出notEnough的信息

### ISSUE THREAD

**Issue by postyizhan** [KKW557/ItemSkin#1]
点击菜单空白格子不应该弹出信息

![图片](https://github.com/KKW557/ItemSkin/assets/97342038/95f6b7f3-5776-47ed-87bb-1adc0f8b89da)

messages.properties
```
prefix=§e物品皮肤 >\u0020

version=§r版本: %s
reloadStart=§r配置重载中...
reloadEnd=§r重载完成.

illegalGroup=§c你输入了非法的物品皮肤组名称!
noGroup=§c该项目不在任何物品皮肤组中!

skinMenu=%s §r(%s/%s)
prePage=<-上一页
nextPage=下一页->
resetSkin=§c重设皮肤

selected=§a已选择.
select=§e点击选择.
locked=§c已上锁.
unlockUnavailable=§c总共需要 §b%s §c硬币来解锁!
require=§c你还需要 §b%s §c硬币!
unlockAvailable=§e点击花费 §b%s §e硬币来解锁!

disableInCreative=§c无法在创意模式下选择物品皮肤!
resetSuccess=§a你选择的物品外观已重置.
selectSuccess=§a你选择的物品外观已设置为§r%s§a.
notHave=§c你没有此物品皮肤.
notEnough=§c你没有足够的硬币来买它.
gotSkin=§a您在物品皮肤上花费了§e%s§a硬币§r%s§a.
```
skins
```
example-wools:
  name: "Example Wools"
  skins:
    default-wool:
      material:
        type: WOOL
    named-wool:
      name: "\u00a7bNamed Wool"
      material:
        type: WOOL
        data: 8
    buyable-wool:
      price: 23.3
      material:
        type: WOOL
        data: 7
    unbuyable-wool:
      material:
        type: WOOL
        data: 15
example-stones:
  name: "Example Stones"
  skins:
    stone:
      material:
        type: STONE
    granite:
      price: 100
      material:
        type: STONE
        data: 1
    polished-granite:
      price: 200
      material:
        type: STONE
        data: 2
    diorite:
      price: 100
      material:
        type: STONE
        data: 3
    polished-diorite:
      price: 200
      material:
        type: STONE
        data: 4
    andesite:
      price: 100
      material:
        type: STONE
        data: 5
    polished-andesite:
      price: 200
      material:
        type: STONE
        data: 6
```
